name: Markdown To PDF

on: push

jobs:
  convert_via_pandoc:
    steps:
      - uses: docker://pandoc/latex:2.10
        with:
          args: "--standalone --template g-brief2 --pdf-engine xelatex --from markdown ./example/letter.md -o letter.pdf"
